import assert from 'node:assert/strict';
import http from 'node:http';
import {spawn} from 'node:child_process';
import {createKeyPair,issueReceipt,signPayload} from '../src/receipts.js';
import {registerTrustedResults} from '../src/submissions.js';
const token='ak-public-test-token', issuer=createKeyPair(), claimant=createKeyPair(), claimantName='public-smoke'; process.env.AK_TRUSTED_ISSUER_PUBLIC_KEY=issuer.publicKey;
const child=spawn(process.execPath,['src/server.js'],{env:{...process.env,PORT:'0',AK_PUBLIC:'1',AK_API_TOKEN:token,AK_TRUSTED_ISSUER_PUBLIC_KEY:issuer.publicKey,AK_BLACKBOX_SECRET:'server-only-blackbox-secret'},stdio:['ignore','pipe','pipe']});
let port=null,log='';child.stdout.on('data',d=>{log+=d.toString();const m=log.match(/http:\/\/[^:]+:(\d+)/);if(m)port=Number(m[1])});
const wait=async()=>{for(let i=0;i<100;i++){if(port)return;await new Promise(r=>setTimeout(r,25))}throw new Error('server did not announce port')};
const req=(p,m='GET',b=null,t=null)=>new Promise((resolve,reject)=>{const h={};if(b)h['content-type']='application/json';if(t)h.authorization=`Bearer ${t}`;const r=http.request({hostname:'127.0.0.1',port,path:p,method:m,headers:h},res=>{let d='';res.on('data',c=>d+=c);res.on('end',()=>resolve({status:res.statusCode,body:d}))});r.on('error',reject);r.end(b?JSON.stringify(b):undefined)});
try{await wait();assert.equal((await req('/api/leaderboard')).status,200);assert.equal((await req('/api/result/result_fake')).status,401);assert.equal((await req('/api/run','POST',{agentId:'mock',taskId:'AK-001'})).status,401);assert.equal((await req('/api/run','POST',{agentId:'mock',taskId:'AK-001'},token)).status,403);const bb=await req('/api/blackbox','POST',{},token);assert.equal(bb.status,201);assert.equal(JSON.parse(bb.body).revealed,false);assert.equal('taskId' in JSON.parse(bb.body),false);const results=[{resultId:'r1',score:90}];await registerTrustedResults(results,{privateKey:issuer.privateKey,publicKey:issuer.publicKey});const receipt=await issueReceipt({suiteId:'public-smoke',resultIds:['r1'],agent:'codex',provider:'openai',model:'smoke',version:'1',track:'core',score:{average:90},results,privateKey:issuer.privateKey,publicKey:issuer.publicKey,trust:'official',issuer:'official-worker',benchmarkCommit:'smoke-commit',oracleHash:'smoke-oracle',metadata:{claimant:claimantName,claimantPublicKey:claimant.publicKey}});const evidence={results,benchmarkCommit:'smoke-commit',oracleHash:'smoke-oracle'};const claimantSignature=signPayload({receipt_id:receipt.receipt_id,claimant:claimantName,nonce:receipt.nonce},claimant.privateKey);const payload={receipt,evidence,claimant:claimantName,claimantPublicKey:claimant.publicKey,claimantSignature};const sub=await req('/api/submissions','POST',payload,token);assert.equal(sub.status,201);assert.equal(JSON.parse(sub.body).trust,'official');const replay=await req('/api/submissions','POST',payload,token);assert.equal(replay.status,409);console.log('PUBLIC API SMOKE OK')}finally{child.kill('SIGTERM')}
