import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createKeyPair,issueReceipt,signPayload,verifyReceipt} from '../src/receipts.js';
import {sha256} from '../src/core.js';
import {canonicalize} from '../src/receipts.js';
import {REPLAY_DIR,MAX_SUBMISSION_PAGE_SIZE,submitPublicReceipt,registerTrustedResults,pruneReplayMarkers} from '../src/submissions.js';

const issuer=createKeyPair();
process.env.AK_TRUSTED_ISSUER_PUBLIC_KEY=issuer.publicKey;
process.env.AK_MAX_OFFICIAL_RECEIPT_LIFETIME_MS=365*24*60*60_000;
const claimant=createKeyPair();
const expiresInMs=10*365*24*60*60_000;
const r=await issueReceipt({suiteId:'v0715',resultIds:['v0715-r'],agent:'a',provider:'p',model:'m',version:'1',track:'core',score:{average:100},results:[{resultId:'v0715-r',score:100}],privateKey:issuer.privateKey,publicKey:issuer.publicKey,trust:'official',issuer:'official-worker',expiresInMs,metadata:{claimant:'alice',claimantPublicKey:claimant.publicKey}});
assert.equal(Math.round((Date.parse(r.expiresAt)-Date.parse(r.issuedAt))/86400000),365,'official receipt lifetime must be capped');
assert.equal(verifyReceipt(r).official,true);
const replayPath=path.join(REPLAY_DIR,`${sha256(canonicalize({receiptId:r.receipt_id,claimant:'alice',claimId:r.claimId,nonce:r.nonce}))}.lock`);
await fs.mkdir(REPLAY_DIR,{recursive:true});
await fs.writeFile(replayPath,JSON.stringify({receiptId:r.receipt_id,claimant:'alice',claimId:r.claimId,nonce:r.nonce,expiresAt:r.expiresAt,claimedAt:new Date(Date.now()-400*24*60*60_000).toISOString()}));
const st=await fs.stat(replayPath);await fs.utimes(replayPath,new Date(st.atime),new Date(Date.now()-400*24*60*60_000));
await pruneReplayMarkers({reconcile:true});
assert.equal(await fs.access(replayPath).then(()=>true,()=>false),true,'replay marker must survive while receipt remains valid');
assert.ok(MAX_SUBMISSION_PAGE_SIZE<=100);
console.log('REVIEW v0.7.15 REPLAY LIFETIME/PUBLIC PAGINATION OK');
const expiredReplayPath=path.join(REPLAY_DIR,'v0715-expired.lock');
await fs.writeFile(expiredReplayPath,JSON.stringify({expiresAt:new Date(Date.now()-400*24*60*60_000).toISOString()})+'\n');
const eold=Date.now()-400*24*60*60_000;await fs.utimes(expiredReplayPath,new Date(eold),new Date(eold));
await pruneReplayMarkers({reconcile:true});
assert.equal(await fs.access(expiredReplayPath).then(()=>true,()=>false),false,'expired receipt replay marker should be prunable');
console.log('REVIEW v0.7.15 REPLAY EXPIRY CLEANUP OK');
const legacy={...r,expiresAt:new Date(Date.parse(r.issuedAt)+2*365*24*60*60_000).toISOString()};
const {signature:ignored,...legacyPayload}=legacy;
legacy.signature=signPayload(legacyPayload,issuer.privateKey);
assert.equal(verifyReceipt(legacy).official,false,'official receipts beyond maximum lifetime must be rejected');
assert.match(verifyReceipt(legacy).reason,/lifetime exceeds/);
console.log('REVIEW v0.7.15 OFFICIAL LIFETIME CAP VERIFIED');
