import crypto from 'node:crypto';
import {loadManifest,loadTask,runId,writeJson,writeResultArtifact,RESULTS_DIR,ROOT} from './core.js';
import {loadGeneratedTasks} from './challenge-pack.js';
const seal=(message,secret)=>crypto.createHmac('sha256',secret).update(String(message)).digest('hex');
export async function selectBlackBox({seed,secret=process.env.AK_BLACKBOX_SECRET}={}){
  const generated=await loadGeneratedTasks();const pool=generated.length?generated:(await loadManifest()).tasks;if(!pool.length)throw new Error('empty challenge pool');
  const effectiveSeed=seed??crypto.randomBytes(24).toString('hex');const key=secret||'LOCAL-DEMO-ONLY';const canonicalPool=pool.map(x=>({id:x.id,slug:x.slug,kind:x.kind,title:x.title,category:x.category,difficulty:x.difficulty,weight:x.weight,generated:!!x.generated,generator:x.generator||null}));const poolDigest=crypto.createHash('sha256').update(JSON.stringify(canonicalPool)).digest('hex');const h=crypto.createHash('sha256').update(String(effectiveSeed)).digest('hex');const idx=parseInt(h.slice(0,8),16)%pool.length;const task=pool[idx];
  const benchmarkVersion=process.env.AK_BENCHMARK_VERSION||'0.7.16';const manifestDigest=crypto.createHash('sha256').update(JSON.stringify(await loadManifest())).digest('hex');const challengeDigest=crypto.createHash('sha256').update(JSON.stringify({benchmarkVersion,manifestDigest,poolDigest})).digest('hex');const commitment=seal(`${effectiveSeed}:${challengeDigest}:${task.id}`,key);return {mode:'blackbox',benchmarkVersion,taskId:task.id,poolDigest,challengeDigest,commitment,issuedAt:new Date().toISOString(),revealed:false,localDemo:!secret};
}
export async function recordBlackBoxSelection(selection,{reveal=false}={}){const id=runId('blackbox');const privateRecord={schema_version:'agent-killer.blackbox.v3',id,createdAt:new Date().toISOString(),...selection};await writeResultArtifact(`${RESULTS_DIR}/${id}.json`,privateRecord);return{schema_version:privateRecord.schema_version,id,createdAt:privateRecord.createdAt,mode:'blackbox',commitment:selection.commitment,revealed:!!reveal,taskId:reveal?selection.taskId:undefined,localDemo:!!selection.localDemo};}
export function revealBlackBox(record,{seed,secret=process.env.AK_BLACKBOX_SECRET}={}){if(!record||!seed||!secret)return{valid:false,reason:'seed and server secret required'};return{valid:seal(`${seed}:${record.challengeDigest}:${record.taskId}`,secret)===record.commitment,taskId:record.taskId,poolDigest:record.poolDigest}}
