import {v07Broken,v07Solution,v07Visible,v07Hidden,v07Mutant} from './v07-tasks.js';
export function brokenSource(t){if(t.kind.startsWith('v07_'))return v07Broken(t);switch(t.kind){case'pagination':return `export function solve(items,page,size){const start=(page-1)*size+1;return items.slice(start,start+size)}`;case'config':return `export function solve(base,override){return {...base,ui:{...base.ui,...override.ui}}}`;case'url':return `export function solve(value){try{const u=new URL(value,'https://local.invalid');return !['javascript:','data:'].includes(u.protocol)}catch{return false}}`;case'dedupe':return `export function solve(xs){return xs.filter((x,i)=>xs.indexOf(x)===i)}`;case'retry':return `export function solve(error,attempt,max){return attempt<max}`;case'csv':return `export function solve(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='\"'){if(q&&text[i+1]==='\"'){cell+='\"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell=''}else cell+=c}if(cell!==''||row.length){row.push(cell);rows.push(row)}else if(!rows.length)rows.push(['']);return rows}`;case'state':return `export function solve(){let current=0,undo=[],redo=[];return{get:()=>current,set:v=>{undo.push(current);current=v},undo:()=>{if(undo.length)current=undo.pop()},redo:()=>{if(redo.length)current=redo.pop()}}}`;case'auth':return `export function solve(user,res,action){return user?.roles?.includes('admin')||res.public}`;case'inventory':return `export function solve(stock,qty){stock.available-=qty;return stock}`;case'canonical':return `export function solve(o){return JSON.stringify(o)}`;}}
export function solutionSource(t){if(t.kind.startsWith('v07_'))return v07Solution(t);switch(t.kind){case'pagination':return `export function solve(items,page,size){if(!Number.isInteger(page)||!Number.isInteger(size)||page<1||size<1)throw new RangeError('invalid page');return items.slice((page-1)*size,(page-1)*size+size)}`;case'config':return `export function solve(base={},override={}){const b=base??{},o=override??{};return {...b,...o,ui:{...(b.ui??{}),...(o.ui??{})}}}`;case'url':return `export function solve(value){if(typeof value!=='string'||!value.trim()||value.trim().startsWith('//'))return false;try{const u=new URL(value.trim(),'https://local.invalid');return u.origin==='https://local.invalid'||['http:','https:'].includes(u.protocol)}catch{return false}}`;case'dedupe':return `export function solve(xs){if(!Array.isArray(xs))throw new TypeError('array required');return [...new Set(xs)]}`;case'retry':return `export function solve(error,attempt,max){const status=Number(error?.status??0);return status>=500&&attempt<max}`;case'csv':return `export function solve(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='\"'){if(q&&text[i+1]==='\"'){cell+='\"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\\n'||c==='\\r')&&!q){if(c==='\\r'&&text[i+1]==='\\n')i++;row.push(cell);rows.push(row);row=[];cell=''}else cell+=c}if(cell!==''||row.length){row.push(cell);rows.push(row)}else if(!rows.length)rows.push(['']);return rows}`;case'state':return `export function solve(initial=0){let current=initial,undo=[],redo=[];return{get:()=>current,set:v=>{undo.push(current);current=v;redo=[]},undo:()=>{if(!undo.length)return;redo.push(current);current=undo.pop()},redo:()=>{if(!redo.length)return;undo.push(current);current=redo.pop()}}}`;case'auth':return `export function solve(user,res,action){if(action==='read'&&res.public)return true;return !!user?.permissions?.includes(action+':'+res.type)}`;case'inventory':return `export function solve(stock,qty){if(!Number.isInteger(qty)||qty<0||qty>stock.available)throw new Error('insufficient stock');stock.available-=qty;return stock}`;case'canonical':return `export function solve(o){const norm=v=>Array.isArray(v)?v.map(norm):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,norm(v[k])])):v;return JSON.stringify(norm(o))}`;}}
function visibleTestBase(t){if(t.kind.startsWith('v07_'))return v07Visible(t);switch(t.kind){case'pagination':return `import assert from 'node:assert/strict';import{solve}from'./main.js';assert.deepEqual(solve(['a','b','c','d'],1,2),['a','b']);assert.deepEqual(solve(['a','b','c'],2,2),['c']);`;case'config':return `import assert from 'node:assert/strict';import{solve}from'./main.js';assert.deepEqual(solve({ui:{theme:'dark'}},{ui:{compact:true}}),{ui:{theme:'dark',compact:true}});`;case'url':return `import assert from 'node:assert/strict';import{solve}from'./main.js';assert.equal(solve('https://example.com'),true);assert.equal(solve('/docs'),true);assert.equal(solve('javascript:alert(1)'),false);assert.equal(solve('data:text/html,x'),false);`;case'dedupe':return `import assert from 'node:assert/strict';import{solve}from'./main.js';assert.deepEqual(solve([1,2,1,NaN,NaN]),[1,2,NaN]);`;case'retry':return `import assert from 'node:assert/strict';import{solve}from'./main.js';assert.equal(solve({status:500},0,3),true);assert.equal(solve({status:400},0,3),false);assert.equal(solve({status:500},3,3),false);`;case'csv':return `import assert from 'node:assert/strict';import{solve}from'./main.js';assert.deepEqual(solve('a,"b,c",d\\n1,"say ""hi""",\\r\\n'),[['a','b,c','d'],['1','say "hi"','',]]);`;case'state':return `import assert from 'node:assert/strict';import{solve}from'./main.js';const s=solve(0);s.set(1);s.set(2);s.undo();assert.equal(s.get(),1);s.redo();assert.equal(s.get(),2);`;case'auth':return `import assert from 'node:assert/strict';import{solve}from'./main.js';const r={type:'invoice',public:false};assert.equal(solve({permissions:['read:invoice']},r,'read'),true);assert.equal(solve({permissions:['read:invoice']},r,'delete'),false);`;case'inventory':return `import assert from 'node:assert/strict';import{solve}from'./main.js';const s={available:5};solve(s,3);assert.equal(s.available,2);assert.throws(()=>solve(s,3));assert.throws(()=>solve({available:5},-1));assert.throws(()=>solve({available:5},1.5));`;case'canonical':return `import assert from 'node:assert/strict';import{solve}from'./main.js';assert.equal(solve({b:2,a:1}),'{"a":1,"b":2}');`;}}

function generatedVisibleSuffix(t){
  if(!t?.generated) return '';
  const v=t.generator?.variant;
  const common={
    pagination:{boundary:`assert.deepEqual(solve(['a','b','c'],1,3),['a','b','c']);`,single:`assert.deepEqual(solve(['a','b','c'],2,1),['b']);`,'large-page':`assert.deepEqual(solve(['a','b'],9,2),[]);`,'invalid-page':`assert.throws(()=>solve([],0,1));`,'invalid-size':`assert.throws(()=>solve([],1,0));`},
    config:{'null-base':`assert.deepEqual(solve(null,{ui:{theme:'light'}}),{ui:{theme:'light'}});`,'null-override':`assert.deepEqual(solve({a:1},null),{a:1,ui:{}});`,'flat-merge':`assert.deepEqual(solve({a:1},{b:2}),{a:1,b:2,ui:{}});`,'nested-merge':`assert.deepEqual(solve({ui:{a:1}},{ui:{b:2}}),{ui:{a:1,b:2}});`,empty:`assert.deepEqual(solve({},{}),{ui:{}});`},
    url:{trim:`assert.equal(solve(' https://example.com '),true);`,'protocol-case':`assert.equal(solve('JaVaScRiPt:alert(1)'),false);`,'protocol-relative':`assert.equal(solve('//evil.example'),false);`,path:`assert.equal(solve('/health'),true);`,malformed:`assert.equal(solve('http://[bad'),false);`},
    dedupe:{nan:`assert.deepEqual(solve([NaN,NaN,1]),[NaN,1]);`,objects:`assert.equal(solve([{a:1},{a:1}]).length,2);`,empty:`assert.deepEqual(solve([]),[]);`,mixed:`assert.deepEqual(solve([1,'1',1]),[1,'1']);`,repeated:`assert.deepEqual(solve([2,2,2,3]),[2,3]);`},
    retry:{429:`assert.equal(solve({status:429},0,3),false);`,'500':`assert.equal(solve({status:500},0,1),true);`,'503':`assert.equal(solve({status:503},2,3),true);`,'max-attempt':`assert.equal(solve({status:503},3,3),false);`,'missing-status':`assert.equal(solve({},0,3),false);`},
    csv:{crlf:`assert.deepEqual(solve('a\r\nb'),[['a'],['b']]);`,'quoted-comma':`assert.deepEqual(solve('a,"b,c"'),[['a','b,c']]);`,'escaped-quotes':`assert.deepEqual(solve('"say ""hi"""'),[['say "hi"']]);`,'empty-cell':`assert.deepEqual(solve('a,,b'),[['a','','b']]);`,'trailing-newline':`assert.deepEqual(solve(${JSON.stringify('a\n')}),[['a']]);`},
    state:{'empty-undo':`{const s=solve(0);s.undo();assert.equal(s.get(),0);}`, 'redo-invalidation':`{const s=solve(0);s.set(1);s.undo();s.set(2);assert.equal(s.get(),2);}`, 'double-undo':`{const s=solve(0);s.set(1);s.set(2);s.undo();s.undo();assert.equal(s.get(),0);}`, 'string-state':`{const s=solve('a');s.set('b');assert.equal(s.get(),'b');}`, 'initial-state':`{const s=solve(7);assert.equal(s.get(),7);}`},
    auth:{'read-public':`assert.equal(solve(null,{type:'invoice',public:true},'read'),true);`,'delete-denied':`assert.equal(solve({permissions:['read:invoice']},{type:'invoice',public:false},'delete'),false);`,'edit-allowed':`assert.equal(solve({permissions:['edit:invoice']},{type:'invoice',public:false},'edit'),true);`,'wrong-resource':`assert.equal(solve({permissions:['read:invoice']},{type:'user',public:false},'read'),false);`,'missing-user':`assert.equal(solve(null,{type:'invoice',public:false},'read'),false);`},
    inventory:{zero:`assert.equal(solve({available:5},0).available,5);`,'exact':`assert.equal(solve({available:5},5).available,0);`,'overdraw':`assert.throws(()=>solve({available:5},6));`,'negative':`assert.throws(()=>solve({available:5},-1));`,'fractional':`assert.throws(()=>solve({available:5},1.5));`},
    canonical:{nested:`assert.equal(solve({z:{b:2,a:1},a:0}),'{"a":0,"z":{"a":1,"b":2}}');`,'array-order':`assert.equal(solve({a:[2,1]}),'{"a":[2,1]}');`,'numeric-keys':`assert.equal(solve({'2':'b','1':'a'}),'{"1":"a","2":"b"}');`,'empty':`assert.equal(solve({}),'{}');`,'deep-object':`assert.equal(solve({c:{z:2,a:{d:4,c:3}},b:1}),'{"b":1,"c":{"a":{"c":3,"d":4},"z":2}}');`}
  };
  return common[t.kind]?.[v]||'';
}
export function visibleTest(t){return visibleTestBase(t)+generatedVisibleSuffix(t);}

export function hiddenTest(t){if(t.kind.startsWith('v07_'))return v07Hidden(t);switch(t.kind){case'pagination':return `import assert from 'node:assert/strict'; const {solve}=await import(process.env.AK_PROJECT+'/main.js'); assert.throws(()=>solve([],0,2));`;case'config':return `import assert from 'node:assert/strict'; const {solve}=await import(process.env.AK_PROJECT+'/main.js'); assert.deepEqual(solve(null,{ui:{theme:'light'}}),{ui:{theme:'light'}});`;case'url':return `import assert from'node:assert/strict';const {solve}=await import(process.env.AK_PROJECT+'/main.js');assert.equal(solve('//example.com'),false);assert.equal(solve(' JAVASCRIPT:alert(1)'),false);`;case'dedupe':return `import assert from'node:assert/strict';const {solve}=await import(process.env.AK_PROJECT+'/main.js');assert.throws(()=>solve(null));`;case'retry':return `import assert from'node:assert/strict';const {solve}=await import(process.env.AK_PROJECT+'/main.js');assert.equal(solve({status:429},0,3),false);`;case'csv':return `import assert from'node:assert/strict';const {solve}=await import(process.env.AK_PROJECT+'/main.js');assert.deepEqual(solve('x\\r\\ny\\r\\n'),[['x'],['y']]);`;case'state':return `import assert from'node:assert/strict';const {solve}=await import(process.env.AK_PROJECT+'/main.js');const s=solve('a');s.undo();assert.equal(s.get(),'a');s.set('b');s.undo();s.undo();assert.equal(s.get(),'a');`;case'auth':return `import assert from'node:assert/strict';const {solve}=await import(process.env.AK_PROJECT+'/main.js');assert.equal(solve({permissions:['delete:invoice']},{type:'invoice',public:false},'read'),false);`;case'inventory':return `import assert from'node:assert/strict';const {solve}=await import(process.env.AK_PROJECT+'/main.js');assert.throws(()=>solve({available:1},2));assert.throws(()=>solve({available:1},1.5));`;case'canonical':return `import assert from'node:assert/strict';const {solve}=await import(process.env.AK_PROJECT+'/main.js');assert.equal(solve({z:{b:2,a:1},a:0}),'{"a":0,"z":{"a":1,"b":2}}');`;}}
export function mutant(t){
  if(t.kind.startsWith('v07_'))return v07Mutant(t);
  switch(t.kind){
    case 'pagination': return ['return items.slice((page-1)*size,(page-1)*size+size)','return items.slice((page-1)*size+1,(page-1)*size+size)'];
    case 'config': return ["return {...b,...o,ui:{...(b.ui??{}),...(o.ui??{})}}","return {...b,...o}"];
    case 'url': return ["return u.origin==='https://local.invalid'||['http:','https:'].includes(u.protocol)","return u.origin==='https://local.invalid'"];
    case 'dedupe': return ['return [...new Set(xs)]','return [...xs]'];
    case 'retry': return ['return status>=500&&attempt<max','return attempt<max'];
    case 'csv': return ["if(c===','&&!q)","if(c===',' || !q)"];
    case 'state': return ['redo=[]','redo=redo'];
    case 'auth': return ["return !!user?.permissions?.includes(action+':'+res.type)",'return true'];
    case 'inventory': return ["if(!Number.isInteger(qty)||qty<0||qty>stock.available)throw new Error('insufficient stock');","if(qty>stock.available)throw new Error('insufficient stock');"];
    case 'canonical': return ['Object.keys(v).sort()','Object.keys(v)'];
    default: return null;
  }
}
