import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import {RUNTIME_ROOT,RESULTS_DIR,sha256,writeJson,runId} from './core.js';
export const RECEIPT_SCHEMA='agent-killer.receipt.v6';
export const SIGNATURE_ALGORITHM='Ed25519-canonical-SHA256-v3';
export const MAX_OFFICIAL_RECEIPT_LIFETIME_MS=Math.min(Math.max(Number(process.env.AK_MAX_OFFICIAL_RECEIPT_LIFETIME_MS||365*24*60*60_000),60_000),365*24*60*60_000);
export const canonicalize=v=>{if(v===undefined)return 'null';if(typeof v==='bigint')return JSON.stringify(String(v));if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(canonicalize).join(',')+']';return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonicalize(v[k])).join(',')+'}'};
export function createKeyPair(){return crypto.generateKeyPairSync('ed25519',{publicKeyEncoding:{format:'pem',type:'spki'},privateKeyEncoding:{format:'pem',type:'pkcs8'}})}
const signingBytes=payload=>Buffer.from(sha256(canonicalize(payload)),'hex');
export function signPayload(payload,privateKey){return crypto.sign(null,signingBytes(payload),privateKey).toString('base64')}
export function verifyPayload(payload,signature,publicKey){try{if(typeof signature!=='string'||signature.length>4096)return false;return crypto.verify(null,signingBytes(payload),publicKey,Buffer.from(signature,'base64'))}catch{return false}}
function fingerprint(pub){return sha256(pub).slice(0,32)}
function trustedPublicKey(){return process.env.AK_TRUSTED_ISSUER_PUBLIC_KEY||null}
const nowMs=()=>Date.now();
export function verifyOfficialReceipt(receipt){const trusted=trustedPublicKey();if(!trusted)return{official:false,reason:'trusted issuer not configured'};if(receipt?.publicKey!==trusted)return{official:false,reason:'receipt key is not configured trusted issuer'};if(receipt?.issuerFingerprint!==fingerprint(trusted))return{official:false,reason:'issuer fingerprint mismatch'};if(receipt?.trust!=='official'||receipt?.issuer!=='official-worker')return{official:false,reason:'official issuer metadata invalid'};if(!receipt.expiresAt||Date.parse(receipt.expiresAt)<=nowMs())return{official:false,reason:'receipt expired'};const issued=Date.parse(receipt.issuedAt);const expires=Date.parse(receipt.expiresAt);if(!Number.isFinite(issued)||!Number.isFinite(expires)||expires-issued>MAX_OFFICIAL_RECEIPT_LIFETIME_MS)return{official:false,reason:'receipt lifetime exceeds configured maximum'};if(!receipt.claimId||!receipt.nonce)return{official:false,reason:'claim binding missing'};const{signature,...payload}=receipt;const verified=verifyPayload(payload,signature,trusted);return{official:verified,reason:verified?'trusted issuer':'signature mismatch'}}
export function verifyReceipt(receipt){if(!receipt)return{valid:false,reason:'unsupported schema'};const legacy=receipt.schema_version==='agent-killer.receipt.v5'&&receipt.signature_algorithm==='Ed25519-canonical-SHA256-v2';if(receipt.schema_version!==RECEIPT_SCHEMA&&!legacy)return{valid:false,reason:'unsupported schema'};if(![SIGNATURE_ALGORITHM,'Ed25519-canonical-SHA256-v2'].includes(receipt.signature_algorithm))return{valid:false,reason:'unsupported signature algorithm'};if(!receipt.signature||!receipt.publicKey)return{valid:false,reason:'missing signature/publicKey'};const{signature,...payload}=receipt;if(!verifyPayload(payload,signature,receipt.publicKey))return{valid:false,reason:'signature mismatch'};const official=legacy?{official:false,reason:'legacy receipt is self-attested only'}:verifyOfficialReceipt(receipt);return{valid:true,selfAttested:true,official:official.official,reason:official.reason,expiresAt:receipt.expiresAt||null}}
export function verifyClaimantSignature(receiptId,claimant,nonceOrSignature,signatureOrKey,maybeKey){try{if(maybeKey===undefined)return verifyPayload({receipt_id:receiptId,claimant},nonceOrSignature,signatureOrKey);return verifyPayload({receipt_id:receiptId,claimant,nonce:nonceOrSignature},signatureOrKey,maybeKey)}catch{return false}}
export function verifyReceiptEvidence(receipt,evidence){try{if(!evidence||typeof evidence!=='object')return{valid:false,reason:'evidence required'};if(receipt?.resultsDigest!==sha256(canonicalize(evidence.results||[])))return{valid:false,reason:'results digest mismatch'};if(receipt?.evidenceDigest&&receipt.evidenceDigest!==sha256(canonicalize(evidence)))return{valid:false,reason:'evidence digest mismatch'};const ids=(evidence.results||[]).map(x=>x.resultId||x.id);if(JSON.stringify(ids)!==JSON.stringify(receipt.resultIds||[]))return{valid:false,reason:'result id mismatch'};return{valid:true}}catch{return{valid:false,reason:'invalid evidence'}}}
export async function loadOrCreateSigningKey(dir=path.join(RUNTIME_ROOT,'keys')){await fs.mkdir(dir,{recursive:true,mode:0o700});const priv=path.join(dir,'ed25519-private.pem'),pub=path.join(dir,'ed25519-public.pem');try{const st=await fs.stat(priv);if((st.mode&0o077)!==0)throw new Error('signing key permissions too broad');return{privateKey:await fs.readFile(priv,'utf8'),publicKey:await fs.readFile(pub,'utf8'),generated:false}}catch(e){if(e?.message==='signing key permissions too broad')throw e}const kp=createKeyPair();await fs.writeFile(priv,kp.privateKey,{mode:0o600});await fs.writeFile(pub,kp.publicKey,{mode:0o644});return{...kp,generated:true}}
export async function signTrustedResult(result,{privateKey=null,publicKey=null}={}){const keys=privateKey&&publicKey?{privateKey,publicKey}:await loadOrCreateSigningKey();const id=result.resultId||result.id;if(!id)throw new Error('trusted result id required');const payload={schema_version:'agent-killer.trusted-result.v3',id,digest:sha256(result),result,issuerFingerprint:fingerprint(keys.publicKey),publicKey:keys.publicKey};return{...payload,signature:signPayload(payload,keys.privateKey)}}
export function verifyTrustedResult(record){if(!record||record.schema_version!=='agent-killer.trusted-result.v3')return false;const{signature,...payload}=record;if(payload.digest!==sha256(payload.result)||!verifyPayload(payload,signature,record.publicKey))return false;const trusted=trustedPublicKey();return Boolean(trusted&&record.publicKey===trusted&&record.issuerFingerprint===fingerprint(trusted))}
export async function issueReceipt({suiteId=null,resultIds=[],agent,provider,model,version,track='core',score,results,metadata={},privateKey=null,publicKey=null,trust='self-attested',issuer='local',benchmarkCommit='unknown',oracleHash='unknown',expiresInMs=30*24*60*60*1000}){
 const keys=privateKey&&publicKey?{privateKey,publicKey}:await loadOrCreateSigningKey();
 if(trust==='official'){const trusted=trustedPublicKey();if(!trusted||trusted!==keys.publicKey)throw new Error('official receipt requires configured trusted issuer key');if(issuer!=='official-worker')throw new Error('official receipt issuer identity invalid')}
 const issuedAt=new Date().toISOString(),lifetimeMs=trust==='official'?Math.min(Math.max(Number(expiresInMs),60_000),MAX_OFFICIAL_RECEIPT_LIFETIME_MS):Math.max(60_000,Number(expiresInMs)||30*24*60*60*1000),expiresAt=new Date(Date.now()+lifetimeMs).toISOString(),claimId=runId('claim'),nonce=crypto.randomBytes(24).toString('base64url');
 const evidence={results:results||[],benchmarkCommit,oracleHash};
 const payload={schema_version:RECEIPT_SCHEMA,signature_algorithm:SIGNATURE_ALGORITHM,receipt_id:runId('receipt'),claimId,nonce,issuedAt,expiresAt,suiteId,resultIds,agent,provider,model,version,track,trust,issuer,score,resultsDigest:sha256(canonicalize(results||[])),evidenceDigest:sha256(canonicalize(evidence)),benchmarkCommit,oracleHash,metadata,publicKey:keys.publicKey,issuerFingerprint:fingerprint(keys.publicKey)};
 const receipt={...payload,signature:signPayload(payload,keys.privateKey)};await writeJson(path.join(RESULTS_DIR,receipt.receipt_id+'.receipt.json'),receipt);return receipt;
}
