import http from 'node:http';
import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {ensureDirs,loadManifest,RESULTS_DIR,VERSION,pruneResultArtifacts,refreshArtifactIndex} from './core.js';
import {probeAgents,loadAgents} from '../adapters/index.js';
import {runOne,runSuite,runAdversarial,runAdversarialSuite,latestSuites,globalLeaderboard,officialLeaderboard} from './runner.js';
import {MAX_EXEC_TIMEOUT_MS,MIN_EXEC_TIMEOUT_MS,DEFAULT_EXEC_TIMEOUT_MS} from './core.js';
import {listAdversarialScenarios} from './adversarial.js';
import {submitPublicReceipt,listSubmissions,listSubmissionsPage,verifySubmission,pruneTrustedResults,pruneSubmissions,pruneReplayMarkers} from './submissions.js';
import {verifyReceipt} from './receipts.js';
import {runGauntlet,runKillChain} from './gauntlet.js';
import {listV07Trials} from './v07.js';
import {generatePack} from './challenge-pack.js';
import {selectBlackBox,recordBlackBoxSelection} from './blackbox.js';
import {dnaFromSuite} from './profiles.js';
import {RemoteExecutionGate} from './resource-governance.js';
await ensureDirs();
await refreshArtifactIndex();
await Promise.all([pruneTrustedResults({reconcile:true}),pruneSubmissions({reconcile:true}),pruneReplayMarkers({reconcile:true})]).catch(()=>{});
const PUBLIC=path.join(path.dirname(fileURLToPath(import.meta.url)),'..','public');
const HOST=process.env.AK_HOST||'127.0.0.1';const requestedPort=Number.isInteger(Number(process.env.PORT))?Number(process.env.PORT):0;const PORT=requestedPort;const PUBLIC_MODE=process.env.AK_PUBLIC==='1';
const ALLOW_REMOTE_RUN=process.env.AK_ALLOW_REMOTE_RUN==='1'&&process.env.AK_OFFICIAL_MODE==='1';const CORS_ORIGIN=process.env.AK_CORS_ORIGIN||(PUBLIC_MODE?'*':`http://${HOST}:${PORT}`);
if(PUBLIC_MODE&&!process.env.AK_API_TOKEN)throw new Error('public mode requires API token');
const TOKEN=process.env.AK_API_TOKEN||'';const jobs=new Map(),rate=new Map();const MAX_JOBS=200,JOB_TTL_MS=30*60_000,MAX_RATE_KEYS=5000,MAX_BODY=128*1024,HEADER_TIMEOUT_MS=10_000,REQUEST_TIMEOUT_MS=20_000;const MAX_ACTIVE_JOBS=Math.min(32,Math.max(1,Number(process.env.AK_MAX_ACTIVE_JOBS??process.env.AK_MAX_ACTIVE_EXECUTIONS)||4));const MAX_QUEUED_JOBS=Math.min(256,Math.max(0,Number(process.env.AK_MAX_QUEUED_JOBS)||32));const MAX_ACTIVE_JOBS_PER_CALLER=Math.min(MAX_ACTIVE_JOBS,Math.max(1,Number(process.env.AK_MAX_ACTIVE_PER_CALLER)||2));const executionGate=new RemoteExecutionGate({maxActive:MAX_ACTIVE_JOBS,maxQueued:MAX_QUEUED_JOBS,maxActivePerCaller:MAX_ACTIVE_JOBS_PER_CALLER});const MAX_JOB_LIFETIME_MS=Math.min(60*60_000,Math.max(60_000,Number(process.env.AK_MAX_JOB_LIFETIME_MS)||30*60_000));const callerKey=req=>PUBLIC_MODE?crypto.createHash('sha256').update(String(req.headers.authorization||'')).digest('hex'):String(req.socket.remoteAddress||'local');const startedAt=Date.now();
setInterval(()=>{pruneResultArtifacts().catch(()=>{});pruneTrustedResults().catch(()=>{});pruneSubmissions().catch(()=>{});pruneReplayMarkers().catch(()=>{});const now=Date.now();for(const[k,v]of rate)if(now-v.last>5*60_000)rate.delete(k);if(rate.size>MAX_RATE_KEYS){const entries=[...rate].sort((a,b)=>a[1].last-b[1].last);for(let i=0;i<rate.size-MAX_RATE_KEYS;i++)rate.delete(entries[i][0])}for(const[id,j]of jobs){if(j.status==='queued'||j.status==='running')continue;if((j.createdAt||0)<now-JOB_TTL_MS)jobs.delete(id)}},60_000).unref();
const securityHeaders={'x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer','permissions-policy':'geolocation=(),camera=(),microphone=()'};
const json=(res,c,d)=>{res.writeHead(c,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':CORS_ORIGIN,...securityHeaders});res.end(JSON.stringify(d));};
const fail=(res,status,code)=>json(res,status,{error:code});
const body=async req=>{const len=Number(req.headers['content-length']||0);if(Number.isFinite(len)&&len>MAX_BODY)throw Object.assign(new Error('body too large'),{publicCode:'request_too_large',status:413});let size=0;const chunks=[];for await(const c of req){size+=c.length;if(size>MAX_BODY){req.destroy();throw Object.assign(new Error('body too large'),{publicCode:'request_too_large',status:413});}chunks.push(c)}if(!chunks.length)return{};let x;try{x=JSON.parse(Buffer.concat(chunks,size).toString('utf8'))}catch{throw Object.assign(new Error('invalid json'),{publicCode:'invalid_json'})}if(!x||typeof x!=='object'||Array.isArray(x))throw Object.assign(new Error('json object required'),{publicCode:'invalid_json'});return x};
const addJob=(id,value)=>{jobs.set(id,value);if(jobs.size>MAX_JOBS){for(const [candidateId,candidate] of jobs){if(candidate.status==='queued'||candidate.status==='running')continue;jobs.delete(candidateId);break}}};
const enqueueRemote=(id,caller,fn,b,deadlineAt)=>{const gate=executionGate.tryEnqueue(caller,{jobId:id,async run(){const current=jobs.get(id);if(!current)return;if(Date.now()>=deadlineAt){jobs.set(id,{...current,status:'error',failedAt:Date.now(),completedAt:Date.now(),error:'job_lifetime_exceeded'});return}jobs.set(id,{...current,status:'running',startedAt:Date.now(),deadlineAt});try{const result=await fn({...b,jobDeadlineAt:deadlineAt});jobs.set(id,{status:'complete',createdAt:jobs.get(id)?.createdAt||Date.now(),startedAt:jobs.get(id)?.startedAt,completedAt:Date.now(),result})}catch(e){jobs.set(id,{status:'error',createdAt:jobs.get(id)?.createdAt||Date.now(),startedAt:jobs.get(id)?.startedAt,completedAt:Date.now(),error:e?.publicCode||'execution_failed'})}}});return gate};const jobId=()=>`job_${Date.now()}_${crypto.randomUUID()}`;const authorized=req=>!PUBLIC_MODE||req.headers.authorization===`Bearer ${TOKEN}`;const rateOk=(req,cryptoEndpoint=false)=>{const key=`${req.socket.remoteAddress||'local'}|${PUBLIC_MODE?'public':'local'}|${cryptoEndpoint?'crypto':'normal'}`,now=Date.now(),limit=cryptoEndpoint?30:120;let x=rate.get(key);if(!x||now-x.windowStart>=60_000)x={windowStart:now,count:0,last:now};x.count++;x.last=now;rate.set(key,x);if(rate.size>MAX_RATE_KEYS){const oldest=[...rate.entries()].sort((a,b)=>a[1].last-b[1].last).slice(0,Math.ceil(rate.size*0.1));for(const[k]of oldest)rate.delete(k)}return x.count<=limit};const safeId=id=>/^[A-Za-z0-9._-]{1,160}$/.test(String(id||''));
const MAX_SUITE_AGENTS=32,MAX_SUITE_TASKS=128,MAX_SUITE_EXECUTIONS=256;
const clampTimeout=v=>{const n=Number(v);return Number.isFinite(n)?Math.min(MAX_EXEC_TIMEOUT_MS,Math.max(MIN_EXEC_TIMEOUT_MS,Math.floor(n))):DEFAULT_EXEC_TIMEOUT_MS};
const sanitizeRemoteBody=(pathname,b)=>{const x={...(b||{})};x.keepWorkspace=false;x.timeoutMs=clampTimeout(x.timeoutMs);if(pathname==='/api/suite'||pathname==='/api/adversarial/suite'){if(Array.isArray(x.agentIds))x.agentIds=[...new Set(x.agentIds.map(String))].slice(0,MAX_SUITE_AGENTS);if(pathname==='/api/suite'&&Array.isArray(x.taskIds))x.taskIds=[...new Set(x.taskIds.map(String))].slice(0,MAX_SUITE_TASKS);if(pathname==='/api/suite'&&Array.isArray(x.agentIds)&&Array.isArray(x.taskIds)&&x.agentIds.length*x.taskIds.length>MAX_SUITE_EXECUTIONS)throw Object.assign(new Error('suite execution limit exceeded'),{publicCode:'suite_execution_limit',status:400});}return x};
const server=http.createServer(async(req,res)=>{req.setTimeout(REQUEST_TIMEOUT_MS,()=>{try{req.destroy()}catch{}});try{
  const u=new URL(req.url,'http://localhost');const cryptoEndpoint=u.pathname==='/api/verify-receipt'||u.pathname==='/api/verify-submission';if(!rateOk(req,cryptoEndpoint))return fail(res,429,'rate_limited');
  if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':CORS_ORIGIN,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization',...securityHeaders});return res.end()}
  if(u.pathname.startsWith('/api/')&&req.method!=='GET'&&!authorized(req))return fail(res,401,'unauthorized');
  if(u.pathname==='/api/health')return json(res,200,{ok:true,service:'agent-killer',version:VERSION,public:PUBLIC_MODE,officialIssuerConfigured:!!process.env.AK_TRUSTED_ISSUER_PUBLIC_KEY,strictMode:process.env.AK_OFFICIAL_MODE==='1',remoteExecutionEnabled:ALLOW_REMOTE_RUN});
  if(u.pathname==='/api/agents')return json(res,200,await probeAgents());
  if(u.pathname==='/api/agents/registry')return json(res,200,await loadAgents());
  if(u.pathname==='/api/tasks')return json(res,200,await loadManifest());
  if(u.pathname==='/api/adversarial')return json(res,200,{tracks:[{id:'core',name:'Core'},{id:'adversarial',name:'Adversarial Arena'}],scenarios:listAdversarialScenarios()});
  if(u.pathname==='/api/v07/trials')return json(res,200,{version:VERSION,trials:await listV07Trials()});
  if(u.pathname==='/api/v07/status'){const trials=await listV07Trials();return json(res,200,{version:VERSION,trialCount:trials.length,theme:'Can you prove you are the best agent?'});}
  if(u.pathname==='/api/leaderboard')return json(res,200,{global:PUBLIC_MODE?await officialLeaderboard():await globalLeaderboard(),official:await officialLeaderboard(),recent:PUBLIC_MODE?[]:await latestSuites()});
  if(u.pathname==='/api/submissions'&&req.method==='GET'){const limit=Number(u.searchParams.get('limit')||50),offset=Number(u.searchParams.get('offset')||0);return json(res,200,await listSubmissionsPage({limit,offset}));}
  if(u.pathname==='/api/passport'&&req.method==='GET')return json(res,200,{name:'Agent Killer Passport',schema:'agent-killer.receipt.v6',algorithm:'Ed25519-canonical-SHA256-v3'});
  if(req.method==='POST'&&u.pathname==='/api/submissions'){if(!PUBLIC_MODE)return fail(res,400,'public_submission_mode_required');try{return json(res,201,await submitPublicReceipt(await body(req)))}catch(e){return fail(res,e?.status||400,e.publicCode||'submission_rejected')}}
  if(req.method==='POST'&&u.pathname==='/api/verify-receipt'){try{return json(res,200,verifyReceipt((await body(req)).receipt))}catch(e){return fail(res,e?.status||400,e?.publicCode||'invalid_receipt')}}
  if(req.method==='POST'&&u.pathname==='/api/verify-submission'){try{const b=await body(req);if(!safeId(b.id))return fail(res,400,'invalid_id');return json(res,200,await verifySubmission(b.id))}catch(e){if(e?.code!=='ENOENT')console.error('[verify-submission]',e?.stack||e);return fail(res,404,'not_found')}}
  if(req.method==='POST'&&u.pathname==='/api/dna'){try{return json(res,200,{profiles:await dnaFromSuite((await body(req)).suite)})}catch(e){return fail(res,e?.status||400,e?.publicCode||'invalid_suite')}}
  if(req.method==='POST'&&u.pathname==='/api/generate'){try{return json(res,201,await generatePack(await body(req)))}catch(e){return fail(res,e?.status||400,e?.publicCode||'generation_failed')}}
  if(req.method==='POST'&&u.pathname==='/api/blackbox'){if(PUBLIC_MODE&&!process.env.AK_BLACKBOX_SECRET)return fail(res,503,'blackbox_unavailable');try{const b=await body(req);const selection=PUBLIC_MODE?await selectBlackBox({secret:process.env.AK_BLACKBOX_SECRET}):await selectBlackBox(b);return json(res,201,await recordBlackBoxSelection(selection))}catch(e){return fail(res,e?.status||400,e?.publicCode||'blackbox_failed')}}
  const remoteRoutes={'/api/gauntlet':runGauntlet,'/api/killchain':runKillChain,'/api/run':runOne,'/api/suite':runSuite,'/api/adversarial/run':runAdversarial};
  if(req.method==='POST'&&remoteRoutes[u.pathname]){if(!ALLOW_REMOTE_RUN)return fail(res,403,'remote_execution_disabled');let b;try{b=sanitizeRemoteBody(u.pathname,await body(req))}catch(e){return fail(res,e?.status||400,e?.publicCode||'invalid_request')}const id=jobId(),caller=callerKey(req),deadlineAt=Date.now()+MAX_JOB_LIFETIME_MS;if(executionGate.queuedCount()>=MAX_QUEUED_JOBS&&executionGate.activeCount()>=MAX_ACTIVE_JOBS)return fail(res,429,'execution_queue_full');if(executionGate.activeFor(caller)>=MAX_ACTIVE_JOBS_PER_CALLER)return fail(res,429,'caller_execution_limit');addJob(id,{status:'queued',createdAt:Date.now(),deadlineAt,caller:caller.slice(0,16)});const gate=enqueueRemote(id,caller,remoteRoutes[u.pathname],b,deadlineAt);if(!gate.accepted){jobs.delete(id);return fail(res,429,gate.reason||'execution_unavailable')}return json(res,202,{jobId:id,status:gate.started?'running':'queued'})}
  if(u.pathname.startsWith('/api/result/')){if(PUBLIC_MODE&&!authorized(req))return fail(res,401,'unauthorized');const id=decodeURIComponent(u.pathname.slice('/api/result/'.length));if(!safeId(id))return fail(res,400,'invalid_id');try{return json(res,200,JSON.parse(await fs.readFile(path.join(RESULTS_DIR,id+'.json'),'utf8')))}catch{return fail(res,404,'not_found')}}
  if(u.pathname.startsWith('/api/job/')){if(PUBLIC_MODE&&!authorized(req))return fail(res,401,'unauthorized');const id=u.pathname.slice('/api/job/'.length);if(!/^job_[A-Za-z0-9_-]{1,180}$/.test(id))return fail(res,400,'invalid_id');const j=jobs.get(id);return json(res,200,j||{status:'unknown'})}
  const rel=u.pathname==='/'?'/index.html':u.pathname.replace(/^\/+/, '/');const p=path.resolve(PUBLIC,rel.replace(/^\/+/,''));if(p!==PUBLIC&&!p.startsWith(PUBLIC+path.sep))return fail(res,403,'forbidden');const ext=path.extname(p),mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'}[ext]||'application/octet-stream';let data;try{data=await fs.readFile(p)}catch(e){return fail(res,e?.code==='ENOENT'?404:500,e?.code==='ENOENT'?'not_found':'internal_error')}res.writeHead(200,{'content-type':mime+'; charset=utf-8','cache-control':'no-store','content-security-policy':"default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'",...securityHeaders});res.end(data);
 }catch(e){if(!res.headersSent){console.error('[agent-killer]',e?.stack||e);fail(res,e?.status||500,e?.publicCode||'internal_error')}}});
server.headersTimeout=HEADER_TIMEOUT_MS;server.requestTimeout=REQUEST_TIMEOUT_MS;server.keepAliveTimeout=5000;
server.on('error',err=>{console.error('[agent-killer-server]',err.code||'server_error');process.exitCode=1;});server.maxConnections=Number(process.env.AK_MAX_CONNECTIONS||128);setInterval(()=>{refreshArtifactIndex().catch(()=>{});},15*60_000).unref();pruneResultArtifacts().catch(()=>{});server.listen(PORT,HOST,()=>{const a=server.address();console.log(`Agent Killer ${VERSION} → http://${HOST}:${a?.port??PORT}`)});
